service: rbac-serverless-poc
frameworkVersion: "2"

custom:
  casbinTableName: "casbin-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [CasbinTable, Arn]
  environment:
    CASBIN_TABLE: ${self:custom.casbinTableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    CasbinTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.casbinTableName}

plugins:
  - serverless-offline
